# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/clk.xdc

# XDC: new/debug.xdc

# Block Designs: bd/hw_svm/hw_svm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm || ORIG_REF_NAME==hw_svm} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_processing_system7_0_0/hw_svm_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_processing_system7_0_0 || ORIG_REF_NAME==hw_svm_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axi_gpio_0_0/hw_svm_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axi_gpio_0_0 || ORIG_REF_NAME==hw_svm_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_xbar_0/hw_svm_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_xbar_0 || ORIG_REF_NAME==hw_svm_xbar_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_ps7_0_axi_periph_0/hw_svm_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw_svm_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_rst_ps7_0_30M_0/hw_svm_rst_ps7_0_30M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_rst_ps7_0_30M_0 || ORIG_REF_NAME==hw_svm_rst_ps7_0_30M_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axi_dma_0_0/hw_svm_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axi_dma_0_0 || ORIG_REF_NAME==hw_svm_axi_dma_0_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axi_smc_0/hw_svm_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axi_smc_0 || ORIG_REF_NAME==hw_svm_axi_smc_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axi_dma_1_0/hw_svm_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axi_dma_1_0 || ORIG_REF_NAME==hw_svm_axi_dma_1_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axi_dma_1_1/hw_svm_axi_dma_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axi_dma_1_1 || ORIG_REF_NAME==hw_svm_axi_dma_1_1} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axi_dma_2_0/hw_svm_axi_dma_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axi_dma_2_0 || ORIG_REF_NAME==hw_svm_axi_dma_2_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axis_to_bram_PCV_0_0/hw_svm_axis_to_bram_PCV_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axis_to_bram_PCV_0_0 || ORIG_REF_NAME==hw_svm_axis_to_bram_PCV_0_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axis_to_bram_Kernel_0_0/hw_svm_axis_to_bram_Kernel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axis_to_bram_Kernel_0_0 || ORIG_REF_NAME==hw_svm_axis_to_bram_Kernel_0_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_axis_to_bram_Bias_0_0/hw_svm_axis_to_bram_Bias_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_axis_to_bram_Bias_0_0 || ORIG_REF_NAME==hw_svm_axis_to_bram_Bias_0_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_PL_CLASSIFIER_w_VOTI_0_0/hw_svm_PL_CLASSIFIER_w_VOTI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_PL_CLASSIFIER_w_VOTI_0_0 || ORIG_REF_NAME==hw_svm_PL_CLASSIFIER_w_VOTI_0_0} -quiet] -quiet

# IP: bd/hw_svm/ip/hw_svm_auto_pc_0/hw_svm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_svm_auto_pc_0 || ORIG_REF_NAME==hw_svm_auto_pc_0} -quiet] -quiet

# XDC: bd/hw_svm/hw_svm_ooc.xdc
