# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.cache/wt [current_project]
set_property parent.project_path C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_output_repo c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/hdl/hw_svm_wrapper.vhd
add_files C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/hw_svm.bd
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_processing_system7_0_0/hw_svm_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_gpio_0_0/hw_svm_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_gpio_0_0/hw_svm_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_gpio_0_0/hw_svm_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_xbar_0/hw_svm_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_rst_ps7_0_30M_0/hw_svm_rst_ps7_0_30M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_rst_ps7_0_30M_0/hw_svm_rst_ps7_0_30M_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_rst_ps7_0_30M_0/hw_svm_rst_ps7_0_30M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_0_0/hw_svm_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_0_0/hw_svm_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_0_0/hw_svm_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_1/bd_ebc4_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_1/bd_ebc4_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_2/bd_ebc4_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_3/bd_ebc4_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_4/bd_ebc4_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_5/bd_ebc4_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_6/bd_ebc4_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_10/bd_ebc4_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_11/bd_ebc4_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_12/bd_ebc4_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_16/bd_ebc4_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_17/bd_ebc4_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_18/bd_ebc4_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_19/bd_ebc4_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_23/bd_ebc4_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_24/bd_ebc4_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_25/bd_ebc4_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_29/bd_ebc4_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_30/bd_ebc4_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_31/bd_ebc4_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_35/bd_ebc4_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_36/bd_ebc4_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_37/bd_ebc4_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_38/bd_ebc4_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_39/bd_ebc4_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_40/bd_ebc4_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_41/bd_ebc4_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_42/bd_ebc4_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_43/bd_ebc4_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_1_0/hw_svm_axi_dma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_1_0/hw_svm_axi_dma_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_1_0/hw_svm_axi_dma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_1_1/hw_svm_axi_dma_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_1_1/hw_svm_axi_dma_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_1_1/hw_svm_axi_dma_1_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_2_0/hw_svm_axi_dma_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_2_0/hw_svm_axi_dma_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_dma_2_0/hw_svm_axi_dma_2_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_auto_pc_0/hw_svm_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/hw_svm_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/constrs_1/new/clk.xdc
set_property used_in_implementation false [get_files C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/constrs_1/new/clk.xdc]

read_xdc C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/constrs_1/new/debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top hw_svm_wrapper -part xc7z020clg400-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hw_svm_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hw_svm_wrapper_utilization_synth.rpt -pb hw_svm_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
