set_property SRC_FILE_INFO {cfile:C:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/constrs_1/new/debug.xdc rfile:../../../TEST_CDMA.srcs/constrs_1/new/debug.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_TEST_CDMA_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_TEST_CDMA_i/axis_to_bram_PCV_0_addr_ram[0]} {design_TEST_CDMA_i/axis_to_bram_PCV_0_addr_ram[1]} {design_TEST_CDMA_i/axis_to_bram_PCV_0_addr_ram[2]} {design_TEST_CDMA_i/axis_to_bram_PCV_0_addr_ram[3]}]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[0]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[1]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[2]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[3]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[4]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[5]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[6]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[7]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[8]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[9]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[10]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[11]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[12]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[13]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[14]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[15]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[16]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[17]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[18]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[19]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[20]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[21]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[22]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[23]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[24]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[25]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[26]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[27]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[28]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[29]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[30]} {design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tdata[31]}]]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list design_TEST_CDMA_i/axi_dma_0_m_axis_mm2s_tvalid]]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list design_TEST_CDMA_i/axis_to_bram_PCV_0_en_ram]]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_TEST_CDMA_i/axis_to_bram_PCV_0_s_axis_tready]]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list design_TEST_CDMA_i/axis_to_bram_PCV_0_we_ram]]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_TEST_CDMA_i/processing_system7_0_FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axi_gpio_0/gpio_io_o[0]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_TEST_CDMA_i/axi_gpio_0/s_axi_aclk]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tready]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tvalid]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_TEST_CDMA_i/axis_to_bram_PCV_0/trig]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_TEST_CDMA_i/axis_to_bram_PCV_0/we_ram]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[1]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[2]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[10]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[13]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[19]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[21]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[24]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[3]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[4]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[5]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[6]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[15]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[16]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[22]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[26]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[29]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[0]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[7]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[8]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[18]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[23]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[25]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[30]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[12]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[9]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[11]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[14]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[17]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[20]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[27]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[28]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/s_axis_tdata[31]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[105]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[176]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[245]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[306]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[333]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[43]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[109]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[165]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[236]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[284]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[332]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[405]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[99]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[48]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[157]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[205]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[279]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[329]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[398]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[23]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[42]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[121]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[183]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[209]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[257]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[319]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[396]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[128]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[211]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[310]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[340]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[407]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[127]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[144]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[271]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[232]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[317]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[374]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[126]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[139]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[214]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[285]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[338]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[397]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[61]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[111]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[179]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[246]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[283]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[378]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[1]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[39]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[102]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[149]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[194]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[261]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[20]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[137]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[201]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[274]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[352]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[390]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[5]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[41]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[98]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[142]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[230]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[288]}]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[326]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[30]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[92]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[143]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[231]}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[303]}]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[334]}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[16]}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[47]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[138]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[173]}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[221]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[280]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[357]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[391]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[9]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[37]}]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[100]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[178]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[244]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[252]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[87]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[154]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[198]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[265]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[362]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[12]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[81]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[40]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[153]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[188]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[278]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[328]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[373]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[21]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[33]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[118]}]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[147]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[234]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[268]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[82]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[71]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[152]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[302]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[228]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[320]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[375]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[15]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[31]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[136]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[148]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[199]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[266]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[344]}]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[386]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[4]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[53]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[96]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[175]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[243]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[287]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[346]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[370]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[114]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[229]}]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[294]}]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[323]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[394]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[29]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[97]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[187]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[272]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[388]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[25]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[35]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[85]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[177]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[237]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[304]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[347]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[32]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[124]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[160]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[225]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[275]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[387]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[69]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[115]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[159]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[213]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[254]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[335]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[381]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[76]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[172]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[241]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[292]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[327]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[38]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[123]}]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[145]}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[226]}]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[269]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[325]}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[393]}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[406]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[13]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[112]}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[73]}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[190]}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[256]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[364]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[26]}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[83]}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[141]}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[242]}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[258]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[339]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[94]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[150]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[217]}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[297]}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[384]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[402]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[89]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[200]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[281]}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[382]}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[17]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[120]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[189]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[255]}]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[336]}]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[385]}]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[2]}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[44]}]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[122]}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[140]}]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[196]}]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[263]}]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[361]}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[27]}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[55]}]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[103]}]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[218]}]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[295]}]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[359]}]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[10]}]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[59]}]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[93]}]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[171]}]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[240]}]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[289]}]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[77]}]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[158]}]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[186]}]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[273]}]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[324]}]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[376]}]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[72]}]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[108]}]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[155]}]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[219]}]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[296]}]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[360]}]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[11]}]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[65]}]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[101]}]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[146]}]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[238]}]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[300]}]
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[356]}]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[363]}]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[91]}]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[162]}]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[215]}]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[277]}]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[399]}]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[95]}]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[57]}]
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[224]}]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[253]}]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[392]}]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[403]}]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[28]}]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[56]}]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[135]}]
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[169]}]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[227]}]
set_property src_info {type:XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[313]}]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[314]}]
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[62]}]
set_property src_info {type:XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[78]}]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[163]}]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[7]}]
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[207]}]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[309]}]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[400]}]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[49]}]
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[106]}]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[210]}]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[293]}]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[369]}]
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[18]}]
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[64]}]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[132]}]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[182]}]
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[192]}]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[259]}]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[353]}]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[74]}]
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[107]}]
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[164]}]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[193]}]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[260]}]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[318]}]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[368]}]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[70]}]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[119]}]
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[223]}]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[299]}]
set_property src_info {type:XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[349]}]
set_property src_info {type:XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[389]}]
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[22]}]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[67]}]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[104]}]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[184]}]
set_property src_info {type:XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[249]}]
set_property src_info {type:XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[290]}]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[355]}]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[58]}]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[80]}]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[170]}]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[239]}]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[301]}]
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[343]}]
set_property src_info {type:XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[45]}]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[86]}]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[151]}]
set_property src_info {type:XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[197]}]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[264]}]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[351]}]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[367]}]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[34]}]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[84]}]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[181]}]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[247]}]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[305]}]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[354]}]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[380]}]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[3]}]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[133]}]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[161]}]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[6]}]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[202]}]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[251]}]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[315]}]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[68]}]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[79]}]
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[220]}]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[270]}]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[316]}]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[371]}]
set_property src_info {type:XDC file:1 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[8]}]
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[60]}]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[116]}]
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[174]}]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[248]}]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[308]}]
set_property src_info {type:XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[321]}]
set_property src_info {type:XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[129]}]
set_property src_info {type:XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[168]}]
set_property src_info {type:XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[212]}]
set_property src_info {type:XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[312]}]
set_property src_info {type:XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[345]}]
set_property src_info {type:XDC file:1 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[0]}]
set_property src_info {type:XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[52]}]
set_property src_info {type:XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[117]}]
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[222]}]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[276]}]
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[348]}]
set_property src_info {type:XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[372]}]
set_property src_info {type:XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[19]}]
set_property src_info {type:XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[90]}]
set_property src_info {type:XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[185]}]
set_property src_info {type:XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[195]}]
set_property src_info {type:XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[262]}]
set_property src_info {type:XDC file:1 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[358]}]
set_property src_info {type:XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[46]}]
set_property src_info {type:XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[130]}]
set_property src_info {type:XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[204]}]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[298]}]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[365]}]
set_property src_info {type:XDC file:1 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[404]}]
set_property src_info {type:XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[66]}]
set_property src_info {type:XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[88]}]
set_property src_info {type:XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[206]}]
set_property src_info {type:XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[282]}]
set_property src_info {type:XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[337]}]
set_property src_info {type:XDC file:1 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[366]}]
set_property src_info {type:XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[14]}]
set_property src_info {type:XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[63]}]
set_property src_info {type:XDC file:1 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[113]}]
set_property src_info {type:XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[180]}]
set_property src_info {type:XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[235]}]
set_property src_info {type:XDC file:1 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[267]}]
set_property src_info {type:XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[350]}]
set_property src_info {type:XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[379]}]
set_property src_info {type:XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[50]}]
set_property src_info {type:XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[134]}]
set_property src_info {type:XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[166]}]
set_property src_info {type:XDC file:1 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[203]}]
set_property src_info {type:XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[311]}]
set_property src_info {type:XDC file:1 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[341]}]
set_property src_info {type:XDC file:1 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[395]}]
set_property src_info {type:XDC file:1 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[110]}]
set_property src_info {type:XDC file:1 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[216]}]
set_property src_info {type:XDC file:1 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[286]}]
set_property src_info {type:XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[342]}]
set_property src_info {type:XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[377]}]
set_property src_info {type:XDC file:1 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[24]}]
set_property src_info {type:XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[54]}]
set_property src_info {type:XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[125]}]
set_property src_info {type:XDC file:1 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[208]}]
set_property src_info {type:XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[291]}]
set_property src_info {type:XDC file:1 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[322]}]
set_property src_info {type:XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[401]}]
set_property src_info {type:XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[51]}]
set_property src_info {type:XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[75]}]
set_property src_info {type:XDC file:1 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[167]}]
set_property src_info {type:XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[191]}]
set_property src_info {type:XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[250]}]
set_property src_info {type:XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[331]}]
set_property src_info {type:XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[36]}]
set_property src_info {type:XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[131]}]
set_property src_info {type:XDC file:1 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[156]}]
set_property src_info {type:XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[233]}]
set_property src_info {type:XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[307]}]
set_property src_info {type:XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[330]}]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/data_out[383]}]
set_property src_info {type:XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/addr_ram[1]}]
set_property src_info {type:XDC file:1 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/addr_ram[3]}]
set_property src_info {type:XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/addr_ram[0]}]
set_property src_info {type:XDC file:1 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_TEST_CDMA_i/axis_to_bram_PCV_0/addr_ram[2]}]
set_property src_info {type:XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:534 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
