# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/hw_svm_axi_smc_0.xci
# IP: The module: 'hw_svm_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/bd_ebc4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_0/bd_ebc4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_1/bd_ebc4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_2/bd_ebc4_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_3/bd_ebc4_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_4/bd_ebc4_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_5/bd_ebc4_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_6/bd_ebc4_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_7/bd_ebc4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_8/bd_ebc4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_9/bd_ebc4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_10/bd_ebc4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_11/bd_ebc4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_12/bd_ebc4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_13/bd_ebc4_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_14/bd_ebc4_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_15/bd_ebc4_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_16/bd_ebc4_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_17/bd_ebc4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_18/bd_ebc4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_19/bd_ebc4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_20/bd_ebc4_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_21/bd_ebc4_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_22/bd_ebc4_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_23/bd_ebc4_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_24/bd_ebc4_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_25/bd_ebc4_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_26/bd_ebc4_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_27/bd_ebc4_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_28/bd_ebc4_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_29/bd_ebc4_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_30/bd_ebc4_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_31/bd_ebc4_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_32/bd_ebc4_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_33/bd_ebc4_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_34/bd_ebc4_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_35/bd_ebc4_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_36/bd_ebc4_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_37/bd_ebc4_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_38/bd_ebc4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_39/bd_ebc4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_40/bd_ebc4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_41/bd_ebc4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_42/bd_ebc4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_43/bd_ebc4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_44/bd_ebc4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_1/bd_ebc4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_1/bd_ebc4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_2/bd_ebc4_arsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_3/bd_ebc4_rsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_4/bd_ebc4_awsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_5/bd_ebc4_wsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_6/bd_ebc4_bsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_10/bd_ebc4_s00a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_11/bd_ebc4_sarn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_12/bd_ebc4_srn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_16/bd_ebc4_s01a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_17/bd_ebc4_sawn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_18/bd_ebc4_swn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_19/bd_ebc4_sbn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_23/bd_ebc4_s02a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_24/bd_ebc4_sarn_1_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_25/bd_ebc4_srn_1_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_29/bd_ebc4_s03a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_30/bd_ebc4_sarn_2_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_31/bd_ebc4_srn_2_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_35/bd_ebc4_s04a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_36/bd_ebc4_sarn_3_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_37/bd_ebc4_srn_3_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_38/bd_ebc4_m00s2a_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_39/bd_ebc4_m00arn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_40/bd_ebc4_m00rn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_41/bd_ebc4_m00awn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_42/bd_ebc4_m00wn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_43/bd_ebc4_m00bn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_svm_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/hw_svm_axi_smc_0.xci
# IP: The module: 'hw_svm_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/bd_ebc4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_0/bd_ebc4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_1/bd_ebc4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_2/bd_ebc4_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_3/bd_ebc4_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_4/bd_ebc4_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_5/bd_ebc4_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_6/bd_ebc4_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_7/bd_ebc4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_8/bd_ebc4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_9/bd_ebc4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_10/bd_ebc4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_11/bd_ebc4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_12/bd_ebc4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_13/bd_ebc4_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_14/bd_ebc4_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_15/bd_ebc4_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_16/bd_ebc4_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_17/bd_ebc4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_18/bd_ebc4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_19/bd_ebc4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_20/bd_ebc4_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_21/bd_ebc4_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_22/bd_ebc4_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_23/bd_ebc4_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_24/bd_ebc4_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_25/bd_ebc4_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_26/bd_ebc4_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_27/bd_ebc4_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_28/bd_ebc4_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_29/bd_ebc4_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_30/bd_ebc4_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_31/bd_ebc4_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_32/bd_ebc4_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_33/bd_ebc4_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_34/bd_ebc4_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_35/bd_ebc4_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_36/bd_ebc4_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_37/bd_ebc4_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_38/bd_ebc4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_39/bd_ebc4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_40/bd_ebc4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_41/bd_ebc4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_42/bd_ebc4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_43/bd_ebc4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_44/bd_ebc4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_1/bd_ebc4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_1/bd_ebc4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_2/bd_ebc4_arsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_3/bd_ebc4_rsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_4/bd_ebc4_awsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_5/bd_ebc4_wsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_6/bd_ebc4_bsw_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_10/bd_ebc4_s00a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_11/bd_ebc4_sarn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_12/bd_ebc4_srn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_16/bd_ebc4_s01a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_17/bd_ebc4_sawn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_18/bd_ebc4_swn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_19/bd_ebc4_sbn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_23/bd_ebc4_s02a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_24/bd_ebc4_sarn_1_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_25/bd_ebc4_srn_1_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_29/bd_ebc4_s03a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_30/bd_ebc4_sarn_2_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_31/bd_ebc4_srn_2_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_35/bd_ebc4_s04a2s_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_36/bd_ebc4_sarn_3_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_37/bd_ebc4_srn_3_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_38/bd_ebc4_m00s2a_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_39/bd_ebc4_m00arn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_40/bd_ebc4_m00rn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_41/bd_ebc4_m00awn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_42/bd_ebc4_m00wn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/bd_0/ip/ip_43/bd_ebc4_m00bn_0_ooc.xdc

# XDC: c:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.srcs/sources_1/bd/hw_svm/ip/hw_svm_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_svm_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
