# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sources_1/bd/embedded_system/ip/embedded_system_auto_us_3/embedded_system_auto_us_3.xci
# IP: The module: 'embedded_system_auto_us_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sources_1/bd/embedded_system/ip/embedded_system_auto_us_3/embedded_system_auto_us_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'embedded_system_auto_us_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sources_1/bd/embedded_system/ip/embedded_system_auto_us_3/embedded_system_auto_us_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embedded_system_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sources_1/bd/embedded_system/ip/embedded_system_auto_us_3/embedded_system_auto_us_3.xci
# IP: The module: 'embedded_system_auto_us_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sources_1/bd/embedded_system/ip/embedded_system_auto_us_3/embedded_system_auto_us_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'embedded_system_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sources_1/bd/embedded_system/ip/embedded_system_auto_us_3/embedded_system_auto_us_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embedded_system_auto_us_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
