set_property MARK_DEBUG true [get_nets hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/trig_axis_to_BRAM_PCV]
set_property MARK_DEBUG true [get_nets hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/s_axis_tready]
set_property MARK_DEBUG true [get_nets hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/s_axis_tvalid]
set_property MARK_DEBUG true [get_nets hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/m_axis_tready]
set_property MARK_DEBUG true [get_nets hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/m_axis_tvalid]

set_property MARK_DEBUG true [get_nets {hw_svm_i/PL_CLASSIFIER_w_VOTI_0/m_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/PL_CLASSIFIER_w_VOTI_0/m_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/PL_CLASSIFIER_w_VOTI_0/m_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[26]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[31]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[0]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[4]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[8]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[14]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[15]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[18]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[19]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[25]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[28]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[30]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[1]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[5]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[11]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[20]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[22]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[24]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[27]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[6]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[9]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[12]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[17]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[21]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[23]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[29]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[2]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[3]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[7]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[10]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[13]}]
set_property MARK_DEBUG true [get_nets {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[16]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list hw_svm_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {hw_svm_i/PL_CLASSIFIER_w_VOTI_0/m_axis_tdata[0]} {hw_svm_i/PL_CLASSIFIER_w_VOTI_0/m_axis_tdata[1]} {hw_svm_i/PL_CLASSIFIER_w_VOTI_0/m_axis_tdata[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[0]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[1]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[2]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[3]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[4]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[5]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[6]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[7]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[8]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[9]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[10]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[11]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[12]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[13]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[14]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[15]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[16]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[17]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[18]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[19]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[20]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[21]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[22]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[23]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[24]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[25]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[26]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[27]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[28]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[29]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[30]} {hw_svm_i/axi_dma_0_m_axis_mm2s_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/m_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/m_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/s_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/s_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list hw_svm_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/trig_axis_to_BRAM_PCV]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
