# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_processing_system7_0_1/design_TEST_CDMA_processing_system7_0_1.xci
# IP: The module: 'design_TEST_CDMA_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_processing_system7_0_1/design_TEST_CDMA_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_TEST_CDMA_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_processing_system7_0_1/design_TEST_CDMA_processing_system7_0_1.xci
# IP: The module: 'design_TEST_CDMA_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_processing_system7_0_1/design_TEST_CDMA_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_TEST_CDMA_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
