# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/design_TEST_CDMA_axi_smc_0.xci
# IP: The module: 'design_TEST_CDMA_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/bd_b9dd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_0/bd_b9dd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_1/bd_b9dd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_2/bd_b9dd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_3/bd_b9dd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_4/bd_b9dd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_5/bd_b9dd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_6/bd_b9dd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_7/bd_b9dd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_8/bd_b9dd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_9/bd_b9dd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_1/bd_b9dd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_1/bd_b9dd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_5/bd_b9dd_s00a2s_0_ooc.xdc

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_6/bd_b9dd_sarn_0_ooc.xdc

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_7/bd_b9dd_srn_0_ooc.xdc

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_8/bd_b9dd_m00s2a_0_ooc.xdc

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_TEST_CDMA_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/design_TEST_CDMA_axi_smc_0.xci
# IP: The module: 'design_TEST_CDMA_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/bd_b9dd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_0/bd_b9dd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_1/bd_b9dd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_2/bd_b9dd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_3/bd_b9dd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_4/bd_b9dd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_5/bd_b9dd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_6/bd_b9dd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_7/bd_b9dd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_8/bd_b9dd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_9/bd_b9dd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_1/bd_b9dd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_1/bd_b9dd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_5/bd_b9dd_s00a2s_0_ooc.xdc

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_6/bd_b9dd_sarn_0_ooc.xdc

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_7/bd_b9dd_srn_0_ooc.xdc

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/bd_0/ip/ip_8/bd_b9dd_m00s2a_0_ooc.xdc

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_TEST_CDMA_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
