# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_auto_pc_0/design_TEST_CDMA_auto_pc_0.xci
# IP: The module: 'design_TEST_CDMA_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_auto_pc_0/design_TEST_CDMA_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_TEST_CDMA_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_auto_pc_0/design_TEST_CDMA_auto_pc_0.xci
# IP: The module: 'design_TEST_CDMA_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/Progetti_prova/TEST_CDMA/TEST_CDMA.srcs/sources_1/bd/design_TEST_CDMA/ip/design_TEST_CDMA_auto_pc_0/design_TEST_CDMA_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_TEST_CDMA_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
