webtalk_init -webtalk_dir C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.sim/sim_1/behav/xsim/xsim.dir/TB_Voting_w_ce_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 21 15:47:43 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f424bfa0-3b71-4e7c-ae9c-55875eb64484" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4cb68f95920a487693cc364e614087a3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "36" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key saif -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6912500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6892_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1110757822 -regid "" -xml C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.sim/sim_1/behav/xsim/xsim.dir/TB_Voting_w_ce_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.sim/sim_1/behav/xsim/xsim.dir/TB_Voting_w_ce_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/work/Master_Degree_Thesis/HW_SVM/HW_SVM.sim/sim_1/behav/xsim/xsim.dir/TB_Voting_w_ce_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
