set_property SRC_FILE_INFO {cfile:C:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/constrs_1/new/clock_constraint.xdc rfile:../../../PYNQ_SVM_CLASSIFIER.srcs/constrs_1/new/clock_constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/State[2]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/State_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg_n_0_[0]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg_n_0_[1]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg_n_0_[2]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg_n_0_[3]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg_n_0_[4]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg[4]/Q}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg_n_0_[5]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Kernel_Bias/count_reg[5]/Q}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_SIPO_PCV/Q[2]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_SIPO_PCV/state_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/Q[0]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/State_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/Q[2]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/State_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg_n_0_[0]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg_n_0_[1]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg_n_0_[2]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg_n_0_[3]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg_n_0_[4]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_FSM/pm_FSM_Voting/count_reg[4]/Q}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/Q[0]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg[4]/Q}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg__0[0]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg__0[1]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg__0[2]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg__0[3]} -source [get_pins {embedded_system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 1 [get_pins {embedded_system_i/PL_CLASSIFIER_w_VOTI_0/U0/PM_Voting/count_clk_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
