# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/debug.xdc

# Block Designs: bd/design_TEST_CDMA/design_TEST_CDMA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA || ORIG_REF_NAME==design_TEST_CDMA} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_processing_system7_0_1/design_TEST_CDMA_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_processing_system7_0_1 || ORIG_REF_NAME==design_TEST_CDMA_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_rst_ps7_0_100M_0/design_TEST_CDMA_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_TEST_CDMA_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_bram_ctrl_0_bram_1/design_TEST_CDMA_axi_bram_ctrl_0_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_axi_bram_ctrl_0_bram_1 || ORIG_REF_NAME==design_TEST_CDMA_axi_bram_ctrl_0_bram_1} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_dma_0_0/design_TEST_CDMA_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_axi_dma_0_0 || ORIG_REF_NAME==design_TEST_CDMA_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_ps7_0_axi_periph_0/design_TEST_CDMA_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_TEST_CDMA_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_axis_to_bram_PCV_0_0/design_TEST_CDMA_axis_to_bram_PCV_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_axis_to_bram_PCV_0_0 || ORIG_REF_NAME==design_TEST_CDMA_axis_to_bram_PCV_0_0} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_smc_0/design_TEST_CDMA_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_axi_smc_0 || ORIG_REF_NAME==design_TEST_CDMA_axi_smc_0} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_xbar_0/design_TEST_CDMA_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_xbar_0 || ORIG_REF_NAME==design_TEST_CDMA_xbar_0} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_auto_pc_0/design_TEST_CDMA_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_auto_pc_0 || ORIG_REF_NAME==design_TEST_CDMA_auto_pc_0} -quiet] -quiet

# IP: bd/design_TEST_CDMA/ip/design_TEST_CDMA_axi_gpio_0_0/design_TEST_CDMA_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_TEST_CDMA_axi_gpio_0_0 || ORIG_REF_NAME==design_TEST_CDMA_axi_gpio_0_0} -quiet] -quiet

# XDC: bd/design_TEST_CDMA/design_TEST_CDMA_ooc.xdc
