# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/clock_constraint.xdc

# Block Designs: bd/embedded_system/embedded_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system || ORIG_REF_NAME==embedded_system} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_axi_bram_ctrl_0_0/embedded_system_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==embedded_system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_axi_bram_ctrl_0_1/embedded_system_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_axi_bram_ctrl_0_1 || ORIG_REF_NAME==embedded_system_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_axi_bram_ctrl_0_2/embedded_system_axi_bram_ctrl_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_axi_bram_ctrl_0_2 || ORIG_REF_NAME==embedded_system_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_axi_gpio_0_0/embedded_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_axi_gpio_0_0 || ORIG_REF_NAME==embedded_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_axi_dma_0_1/embedded_system_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_axi_dma_0_1 || ORIG_REF_NAME==embedded_system_axi_dma_0_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_xbar_0/embedded_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_xbar_0 || ORIG_REF_NAME==embedded_system_xbar_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_ps7_0_axi_periph_0/embedded_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==embedded_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_system_ila_0_0/embedded_system_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_system_ila_0_0 || ORIG_REF_NAME==embedded_system_system_ila_0_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_PL_CLASSIFIER_w_VOTI_0_0/embedded_system_PL_CLASSIFIER_w_VOTI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_PL_CLASSIFIER_w_VOTI_0_0 || ORIG_REF_NAME==embedded_system_PL_CLASSIFIER_w_VOTI_0_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_processing_system7_0_0/embedded_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_processing_system7_0_0 || ORIG_REF_NAME==embedded_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_rst_ps7_0_50M_0/embedded_system_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_rst_ps7_0_50M_0 || ORIG_REF_NAME==embedded_system_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_pc_3/embedded_system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_pc_3 || ORIG_REF_NAME==embedded_system_auto_pc_3} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_us_0/embedded_system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_us_0 || ORIG_REF_NAME==embedded_system_auto_us_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_us_1/embedded_system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_us_1 || ORIG_REF_NAME==embedded_system_auto_us_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_us_2/embedded_system_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_us_2 || ORIG_REF_NAME==embedded_system_auto_us_2} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_ds_0/embedded_system_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_ds_0 || ORIG_REF_NAME==embedded_system_auto_ds_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_pc_0/embedded_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_pc_0 || ORIG_REF_NAME==embedded_system_auto_pc_0} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_ds_1/embedded_system_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_ds_1 || ORIG_REF_NAME==embedded_system_auto_ds_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_pc_1/embedded_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_pc_1 || ORIG_REF_NAME==embedded_system_auto_pc_1} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_ds_2/embedded_system_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_ds_2 || ORIG_REF_NAME==embedded_system_auto_ds_2} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_ds_3/embedded_system_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_ds_3 || ORIG_REF_NAME==embedded_system_auto_ds_3} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_ds_4/embedded_system_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_ds_4 || ORIG_REF_NAME==embedded_system_auto_ds_4} -quiet] -quiet

# IP: bd/embedded_system/ip/embedded_system_auto_pc_2/embedded_system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embedded_system_auto_pc_2 || ORIG_REF_NAME==embedded_system_auto_pc_2} -quiet] -quiet

# XDC: bd/embedded_system/embedded_system_ooc.xdc
