@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 06 16:33:42 +0100 2022
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim TB_axis_to_bram_PCV_behav -key {Behavioral:sim_1:Functional:TB_axis_to_bram_PCV} -tclbatch TB_axis_to_bram_PCV.tcl -protoinst "protoinst_files/bd_1412.protoinst" -protoinst "protoinst_files/embedded_system.protoinst" -view C:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sim_1/imports/Multiclass_Classifier_SVM_2/TB_CLASSIFIER_w_VOTING_time_impl.wcfg -view C:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sim_1/imports/Multiclass_Classifier_SVM_2/TB_CLASSIFIER_w_VOTING_time_synth.wcfg -view C:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/PYNQ_SVM_CLASSIFIER.srcs/sim_1/imports/Multiclass_Classifier_SVM_2/TB_CLASSIFIER_w_VOTING_behav.wcfg -view C:/Users/yoxo/OneDrive/Documenti/work_dir/Master_Degree_Thesis/PYNQ_SVM_CLASSIFIER/TB_axis_to_bram_PCV_time_synth.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
